# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 20, 231, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 91, 31))
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 111, 21))
        self.label_4.setObjectName("label_4")
        self.encrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_btn.setGeometry(QtCore.QRect(170, 300, 93, 28))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setGeometry(QtCore.QRect(410, 300, 93, 28))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.plainText_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.plainText_txt.setGeometry(QtCore.QRect(130, 90, 401, 91))
        self.plainText_txt.setObjectName("plainText_txt")
        self.cipherText_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.cipherText_txt.setGeometry(QtCore.QRect(130, 200, 401, 87))
        self.cipherText_txt.setObjectName("cipherText_txt")
        self.signature_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.signature_txt.setGeometry(QtCore.QRect(670, 200, 401, 87))
        self.signature_txt.setObjectName("signature_txt")
        self.Verify_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Verify_btn.setGeometry(QtCore.QRect(950, 300, 93, 28))
        self.Verify_btn.setObjectName("Verify_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 90, 111, 31))
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.sign_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sign_btn.setGeometry(QtCore.QRect(710, 300, 93, 28))
        self.sign_btn.setObjectName("sign_btn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 200, 111, 21))
        self.label_5.setObjectName("label_5")
        self.information_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.information_txt.setGeometry(QtCore.QRect(670, 90, 401, 87))
        self.information_txt.setObjectName("information_txt")
        self.generateKeys_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generateKeys_btn.setGeometry(QtCore.QRect(640, 40, 93, 28))
        self.generateKeys_btn.setObjectName("generateKeys_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA CIPHER - rsa.ui"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">RSA Cipher</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Plain Text:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Cipher Text:</span></p></body></html>"))
        self.encrypt_btn.setText(_translate("MainWindow", "Encrypt"))
        self.decrypt_btn.setText(_translate("MainWindow", "Decrypt"))
        self.Verify_btn.setText(_translate("MainWindow", "Verify"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Information:</span></p></body></html>"))
        self.sign_btn.setText(_translate("MainWindow", "Sign"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Signature:</span></p></body></html>"))
        self.generateKeys_btn.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
